# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-all-tfstates-123456789"
    encrypt = true
    key     = "BlogDevOpsHub/terraform.tfstate"
    region  = "us-east-1"
  }
}
